### ISSUE TITLE
Installation issue OSX El Capitan

### ISSUE THREAD

**Issue by joost** [D-Alex/ropencv#41]
Got the following error installing the gem:

```
gem install ropencv
Fetching: rbind-0.0.27.gem (100%)
Successfully installed rbind-0.0.27
Fetching: ropencv-0.0.21.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ropencv:
	ERROR: Failed to build gem native extension.

    /Users/joost/.rbenv/versions/2.2.1/bin/ruby -r ./siteconf20160508-41096-ph01tj.rb extconf.rb
extconf.rb:3:in `block in <main>': CMake Configure Error (RuntimeError)
	from extconf.rb:1:in `chdir'
	from extconf.rb:1:in `<main>'

extconf failed, exit code 1
```

Running ruby 2.2.1p85 (via rbenv) and installen opencv via Homebrew.

```
> brew info opencv
homebrew/science/opencv: stable 2.4.12 (bottled), HEAD
Open source computer vision library
http://opencv.org/
/usr/local/Cellar/opencv/2.4.12_2 (261 files, 35.6M) *
  Poured from bottle
```

Suggestions welcome :)

**Comment by joost** [comment]
```brew install cmake``` did the trick.
